GLOBAL_CONFIG:
  CHECKPOINT_DIRECTORY: model/
  DATA_DIRECTORY: data/
  EMBEDDING_DIMENSIONS: 400
  EPOCHS: 10
  JSON_EXPORT_FILE: graph
  NUM_PARTITIONS: 1
  PBG_CONFIG_NAME: config.json
  PROJECT_NAME: marvel
  TRAIN_SPLIT: null
  TSV_FILE_NAME: graph
GRAPH_DATABASE:
  PASSWORD: test
  URL: bolt://localhost:7687/
  USERNAME: neo4j
OPTIONAL_PBG_SETTINGS:
  background_io: false
  batch_size: 1000
  bias: false
  bucket_order: inside_out
  checkpoint_preservation_interval: null
  comparator: dot
  disable_lhs_negs: false
  disable_rhs_negs: false
  distributed_init_method: null
  distributed_tree_init_order: true
  dynamic_relations: false
  eval_fraction: 0.0
  eval_num_batch_negs: 1000
  eval_num_uniform_negs: 1000
  global_emb: true
  hogwild_delay: 2.0
  init_path: null
  init_scale: 0.001
  loss_fn: softmax
  lr: 0.1
  margin: 0.1
  max_norm: null
  num_batch_negs: 50
  num_edge_chunks: 1
  num_machines: 1
  num_partition_servers: -1
  num_uniform_negs: 1000
  operator: complex_diagonal
  relation_lr: null
  verbose: 0
  workers: null
SIMILARITY_SEARCH_CONFIG:
  FAISS_INDEX_NAME: IndexIVFFlat
  NEAREST_NEIGHBORS: 5
  NUM_CLUSTER: 5
